server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jonathanvictoricadh/practica-pre-final
          default-label: pre-final
          force-pull: true
          search-paths: configData
