server:
  port: ${PORT:${SERVER_PORT:9003}}
spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-contenedor
    port: 5672
  zipkin:
    baseUrl: http://zipkin-contenedor:9411/
  application:
    name: api-sugeridos
  data:
    mongodb:
      authentication-database: admin
      username: usr-spotify-mongo
      password: pwd-spotify-mongo
      database: spotify-dev-mongo
      port: 5566
      host: mongo-contenedor
    
    
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: false
      serviceURL:
         defaultZone: http://eureka-server:8761/eureka