server:
  port: ${PORT:${SERVER_PORT:9003}}
spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-contenedor
    port: 5672
  zipkin:
    baseUrl: http://zipkin-contenedor:9411/
  application:
    name: api-sugeridos
  data:
    mongodb:
      username: usrspotifymongo
      password: pwdspotifymongo
      database: spotifydevmongo
      port: 27017
      host: mongocontenedor
    
    
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: false
      serviceURL:
         defaultZone: http://eureka-server:8761/eureka