server:
  port: ${PORT:${SERVER_PORT:9001}}
spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-contenedor
    port: 5672
  zipkin:
    baseUrl: http://zipkin-contenedor:9411/
  application:
    name: api-music
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-contenedor:3306/spotify-dev-mysql
    username: usr-spotify-mysql
    password: pwd-spotify-mysql
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
    
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: false
      serviceURL:
         defaultZone: http://eureka-server:8761/eureka