server:
  port: ${PORT:${SERVER_PORT:9003}}
spring:
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-contenedor
    port: 5672
  zipkin:
    baseUrl: http://zipkin-contenedor:9411/
  application:
    name: api-sugeridos
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mongo-contenedor:5566/spotify-dev-mongo
    username: usr-spotify-mongo
    password: pwd-spotify-mongo
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
    
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: false
      serviceURL:
         defaultZone: http://eureka-server:8761/eureka