server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
  application:
    name: api-music
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spotify-dev-mysql
    username: usr-spotify-mysql
    password: pwd-spotify-mysql
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
    
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: false
      serviceURL:
         defaultZone: http://localhost:8761/eureka